### ISSUE TITLE
Uncaught ReferenceError: JST is not defined

### ISSUE THREAD

**Issue by swordray** [jfirebaugh/skim#46]
What is `JST` and where to find it?

In Rails project:

```coffee
# app/assets/javascripts/application.coffee
#= require skim
JST['index']
```

```ruby
# Gemfile
gem 'skim', git: 'https://github.com/jfirebaugh/skim'
gem 'rails', '4.2.2'
```

**Comment by gkopylov** [comment]
JST stands for "Javascript Templates". When you add jst template files to manifest file, sprockets automatically create JST object which contains name of template files and corresponding functions for it.

For example, create file app/assets/javascripts/some_template.jst.skim with the following content:
```
p Hello world!
```
and add this file to the manifest file(application.js):
```
//= require some_template
```
you can access compiled template with this ```JST['some_template']()```, so it will return ```"<p>Hello world!</p>"```

**Comment by swordray** [comment]
@gkopylov Thank you!
